remove the user-declared copy assignment operator to silence warning
error: definition of implicit copy constructor for 'Value<T>' is
deprecated because it has a user-declared copy assignment operator